### ISSUE TITLE
[Starmap Buffs] Disable star info hover while at system scale zoom

### ISSUE THREAD

**Issue by riking** [brotchie/Quality-Mods-Program#2]
When zoomed in far enough to clearly see the planets, hovering over stars in the background shouldn't cause the info to pop up, causing annoying flashes of content.

**Comment by brotchie** [comment]
Thanks for the suggestion Kane. Will take a look this weekend. Should be able to look at the distance of camera from local star to work when auto switching is annoying or not.

**Comment by brotchie** [comment]
Fixed this in latest release. PTAL and let me know if it works for you!

https://dsp.thunderstore.io/package/brotchie/StarmapBuffs/1.0.1/
